# agents/business_travel/agent.py

import datetime
import json
import logging
import uuid
from typing import Any

from a2a.client import ClientFactory
from a2a.types import Message, Part, Role, SendMessageRequest
from openai import AsyncOpenAI

from utilities.blockchain.business_agent_registry_discovery import (
    discover_all_provider_endpoints,
)
from utilities.blockchain.business_travel_booking_client import (
    BookingClientError,
    submit_verified_booking_for_decision,
)
from utilities.smart_contract.smart_contract_client import SmartContractClient

logger = logging.getLogger(__name__)


class TravelPlanningState:
    """Per-context state for a multi-turn business travel conversation."""

    def __init__(self):
        self.origin: str | None = None
        self.destination: str | None = None
        self.appointment_time: str | None = None
        self.time_mode: str = "unknown"
        self.language: str = "de"
        self.selected_offer: dict | None = None
        self.policy_decision: dict | None = None


class BusinessTravelAgent:
    """Coordinates business travel planning via A2A provider agents.

    Architecture contracts:
    - Provider agents supply raw travel offers via A2A.
    - SmartContractClient makes the final policy-based offer selection.
    - All user-facing text is generated by the LLM (_render_user_response_with_llm).
    - The LLM never selects offers, evaluates prices, or applies policy.
    """

    SUPPORTED_CONTENT_TYPES = ["text", "text/plain"]

    def __init__(self):
        self._smart_contract = SmartContractClient()
        self._sessions: dict[str, TravelPlanningState] = {}
        self._provider_clients: dict[str, Any] = {}
        self._openai: AsyncOpenAI | None = None

        endpoints = discover_all_provider_endpoints(use_fallback=False)
        self._rail_url: str = self._require_provider_endpoint(endpoints, "rail")
        self._flight_url: str = self._require_provider_endpoint(endpoints, "flight")
        self._mobility_url: str = self._require_provider_endpoint(endpoints, "mobility")
        logger.info(
            "Provider endpoints resolved via registry: rail=%s flight=%s mobility=%s",
            self._rail_url, self._flight_url, self._mobility_url,
        )

    @staticmethod
    def _require_provider_endpoint(endpoints: dict, capability: str) -> str:
        """Returns the discovered endpoint or raises RuntimeError — no local fallback."""
        endpoint, error = endpoints[capability]
        if endpoint is None:
            raise RuntimeError(
                f"No active provider endpoint found in BusinessAgentRegistry for "
                f"capability '{capability}'. "
                "Provider discovery must succeed via blockchain registry. "
                f"No local fallback is allowed. Reason: {error}"
            )
        return endpoint

    def _get_state(self, context_id: str) -> TravelPlanningState:
        if context_id not in self._sessions:
            self._sessions[context_id] = TravelPlanningState()
        return self._sessions[context_id]

    def _get_openai(self) -> AsyncOpenAI:
        """Returns the shared AsyncOpenAI client, creating it lazily on first use."""
        if self._openai is None:
            self._openai = AsyncOpenAI()
        return self._openai

    # -----------------------------------------------------------------------
    # A2A provider calls
    # -----------------------------------------------------------------------

    async def _call_provider_agent(self, agent_url: str, payload: dict) -> Any:
        """Sends a JSON payload to a provider agent via A2A and returns parsed JSON."""
        if agent_url not in self._provider_clients:
            factory = ClientFactory()
            self._provider_clients[agent_url] = await factory.create_from_url(agent_url)
        client = self._provider_clients[agent_url]

        request = SendMessageRequest(
            message=Message(
                message_id=uuid.uuid4().hex,
                role=Role.ROLE_USER,
                parts=[Part(text=json.dumps(payload, ensure_ascii=False))],
                context_id="",
            )
        )

        response_parts: list[str] = []
        async for result in client.send_message(request):
            field = result.WhichOneof("payload")
            if field == "message":
                for part in result.message.parts:
                    if getattr(part, "text", None):
                        response_parts.append(part.text)
            elif field == "task":
                if result.task.status.HasField("message"):
                    for part in result.task.status.message.parts:
                        if getattr(part, "text", None):
                            response_parts.append(part.text)

        combined = "\n".join(response_parts)
        try:
            return json.loads(combined)
        except json.JSONDecodeError as exc:
            raise ValueError(
                f"Provider agent at {agent_url} returned non-JSON: {combined[:200]}"
            ) from exc

    async def _search_rail_options(
        self, origin: str, destination: str, appointment_time: str
    ) -> list[dict]:
        logger.info(f"Calling RailProviderAgent: {origin} -> {destination}")
        result = await self._call_provider_agent(self._rail_url, {
            "origin": origin, "destination": destination, "appointment_time": appointment_time,
        })
        return result if isinstance(result, list) else []

    async def _search_flight_options(
        self, origin: str, destination: str, appointment_time: str
    ) -> list[dict]:
        logger.info(f"Calling FlightProviderAgent: {origin} -> {destination}")
        result = await self._call_provider_agent(self._flight_url, {
            "origin": origin, "destination": destination, "appointment_time": appointment_time,
        })
        return result if isinstance(result, list) else []

    async def _get_airport_transfers(
        self,
        origin: str,
        destination: str,
        departure_airport: str,
        arrival_airport: str,
    ) -> dict:
        logger.info(f"Calling MobilityProviderAgent: {departure_airport} -> {arrival_airport}")
        result = await self._call_provider_agent(self._mobility_url, {
            "origin": origin, "destination": destination,
            "departure_airport": departure_airport, "arrival_airport": arrival_airport,
        })
        return result if isinstance(result, dict) else {}

    # -----------------------------------------------------------------------
    # Offer preparation
    # -----------------------------------------------------------------------

    def _combine_flight_with_transfers(self, flight: dict, transfers: dict) -> dict:
        """Builds a single policy-checkable offer from a flight and its transfer data."""
        return {
            "offer_id": f"{flight['offer_id']}-with-transfers",
            "mode": "flight_with_transfers",
            "provider": flight["provider"],
            "carrier": flight.get("carrier"),
            "total_price": flight["flight_price"] + transfers.get("total_transfer_price", 0),
            "duration_minutes": (
                flight["flight_duration_minutes"]
                + transfers.get("total_transfer_duration_minutes", 0)
            ),
            "travel_class": flight["travel_class"],
            "provider_reputation": flight["provider_reputation"],
            "arrival_buffer_minutes": flight["arrival_buffer_minutes"],
            "transfers_included": transfers.get("transfers_available") is True,
            "departure_airport": flight["departure_airport"],
            "arrival_airport": flight["arrival_airport"],
            "transfer_details": transfers,
        }

    async def _build_offers(
        self, origin: str, destination: str, appointment_time: str
    ) -> list[dict]:
        """Collects rail and flight-with-transfer offers for SmartContractClient.

        All offer types are always fetched. Policy decisions (rail preference,
        budget, class) belong exclusively to SmartContractClient.
        """
        rail_options = await self._search_rail_options(origin, destination, appointment_time)

        flight_options = await self._search_flight_options(origin, destination, appointment_time)
        combined_flights: list[dict] = []
        for flight in flight_options:
            if flight.get("departure_airport") and flight.get("arrival_airport"):
                transfers = await self._get_airport_transfers(
                    origin, destination,
                    flight["departure_airport"],
                    flight["arrival_airport"],
                )
                combined_flights.append(self._combine_flight_with_transfers(flight, transfers))

        return rail_options + combined_flights

    # -----------------------------------------------------------------------
    # LLM: state update and response rendering
    # -----------------------------------------------------------------------

    async def _update_travel_state_with_llm(
        self, query: str, state: TravelPlanningState
    ) -> dict:
        """Classifies user intent and extracts explicit slot values from the current message.

        For 'plan_trip': returns only what the user explicitly stated — no carry-over from state.
        For 'slot_fill': returns merged values (existing state + new message).
        Offer selection, policy evaluation, and pricing remain in SmartContractClient.
        """
        today = datetime.date.today()
        today_str = today.strftime("%d.%m.%Y")
        today_weekday_en = today.strftime("%A")
        currently_missing = [
            s for s in ("origin", "destination", "appointment_time")
            if not getattr(state, s, None)
        ]
        system_prompt = (
            "You are a travel intent parser for a business travel system.\n"
            "You receive the current known travel state and a new user message.\n"
            "Return a JSON object with exactly these keys:\n\n"
            '{\n'
            '  "intent": "plan_trip" | "slot_fill" | "book_selected_offer" | "modify_trip" | "unknown",\n'
            '  "language": "de" | "en",\n'
            '  "origin": <city string or null>,\n'
            '  "destination": <city string or null>,\n'
            '  "appointment_time": <"DD.MM.YYYY HH:mm" or null — see rules below>,\n'
            '  "time_mode": "departure" | "arrival" | "unknown",\n'
            '  "missing_slots": [<still-null slot names from: "origin", "destination", "appointment_time">],\n'
            '  "follow_up_question": <single question in detected language for ALL missing slots, or null>,\n'
            '  "confidence": <0.0-1.0>\n'
            '}\n\n'
            "=== APPOINTMENT_TIME FORMAT ===\n"
            f"Today is {today_str} ({today_weekday_en}).\n"
            "appointment_time MUST be in 'DD.MM.YYYY HH:mm' format. Examples: '24.06.2026 10:00', '15.06.2026 14:30'.\n"
            "appointment_time is ONLY non-null when BOTH a concrete date AND a time are fully determinable:\n"
            "- 'Montag um 10 Uhr' → compute next Monday from today, format as DD.MM.YYYY 10:00.\n"
            "- 'morgen um 14 Uhr' → tomorrow as DD.MM.YYYY 14:00.\n"
            "- 'am 24.06.2026 um 10' → '24.06.2026 10:00'.\n"
            "- '24.06. um 10' → '24.06.2026 10:00' (use current year; if past, use next year).\n"
            "- 'nächsten Dienstag um 9:30' → date of next Tuesday + '09:30'.\n"
            "- If year is missing: use current year (2026) unless that date is already past, then 2027.\n"
            "- Date given but NO time → appointment_time = null. Must ask for time.\n"
            "- Time given but NO date → appointment_time = null. Must ask for date.\n"
            "- 'im Juni', 'nächsten Monat', 'Montag' (alone, no time) → null. Too vague.\n\n"
            "=== INTENT RULES ===\n"
            "- 'plan_trip': user introduces a NEW travel request containing an explicit DESTINATION "
            "keyword ('nach X', 'nach Berlin', 'to Vienna', 'Ziel: X'). "
            "Extract ONLY slots explicitly stated in THIS message. All unmentioned slots = null.\n"
            "- 'slot_fill': user is answering a follow-up question — providing a missing origin, time, "
            "or date. The message does NOT contain a new destination. "
            "Carry over existing slots from current_state; only update the newly mentioned slot(s).\n"
            "- 'modify_trip': user explicitly replaces a slot of an already-planned trip.\n"
            "- 'book_selected_offer': user wants to book ('buchen', 'bestätigen', 'confirm', 'yes book it').\n"
            "- 'unknown': cannot classify.\n\n"
            "=== DISAMBIGUATION: plan_trip vs slot_fill ===\n"
            "Use 'slot_fill' (NEVER 'plan_trip') when the message:\n"
            "  - Provides ONLY a time or date ('Montag um 10', 'um 14 Uhr', 'am 24.06. um 10').\n"
            "  - Provides ONLY an origin city ('von Dortmund', 'ab Köln', 'from Berlin').\n"
            "  - Provides origin + time but NO destination ('von Dortmund am 24.06. um 10').\n"
            "  - Provides just a city that is not a destination ('München' after already knowing dest=München).\n"
            "  - currently_missing_slots contains 'appointment_time' and the user gives only a time/date.\n"
            "Use 'plan_trip' ONLY when the message explicitly contains a travel destination keyword.\n"
            "Rule: A message WITHOUT 'nach X' / 'to X' / 'Ziel: X' is NEVER 'plan_trip'.\n\n"
            "=== FOLLOW-UP QUESTION RULES ===\n"
            "Combine ALL missing slots in ONE question. Do NOT ask for already-known slots.\n"
            "Examples:\n"
            "  - missing=[origin, appointment_time], dest=München: "
            "'Von wo reisen Sie, und an welchem Datum um wie viel Uhr müssen Sie in München sein?'\n"
            "  - missing=[appointment_time], orig=Dortmund, dest=München: "
            "'An welchem Datum und um wie viel Uhr müssen Sie in München ankommen?'\n"
            "  - missing=[origin], dest=München, time known: 'Von wo reisen Sie nach München?'\n"
            "  - missing=[destination, appointment_time], orig=Dortmund: "
            "'Wohin reisen Sie und an welchem Datum um wie viel Uhr?'\n"
            "  - appointment_time has date but no time: 'Um wie viel Uhr müssen Sie ankommen?'\n"
            "  - appointment_time has time but no date: 'An welchem Datum ist die Reise?'\n\n"
            "=== CRITICAL RULES ===\n"
            "- A slot may ONLY be non-null if EXPLICITLY stated in the current message.\n"
            "- NEVER infer, guess, assume, or copy slot values from general knowledge.\n"
            "- 'missing_slots' lists every slot that is null after applying intent-based logic.\n"
            "- missing_slots must NEVER be [] unless all three (origin, destination, appointment_time) are present.\n"
            "- For 'plan_trip': missing_slots computed from the current message only (ignore current_state).\n"
            "- For 'slot_fill'/'modify_trip': missing_slots computed after merging with current_state.\n"
            "- For 'book_selected_offer': missing_slots = [].\n"
            "- NEVER select offers, evaluate prices, apply policy, or invent travel options.\n\n"
            f"Current state (for slot_fill/modify_trip merging ONLY — ignore for plan_trip):\n"
            f"origin={state.origin or 'null'}, destination={state.destination or 'null'}, "
            f"appointment_time={state.appointment_time or 'null'}, language={state.language}\n"
            f"currently_missing_slots={json.dumps(currently_missing)}"
        )

        try:
            response = await self._get_openai().chat.completions.create(
                model="gpt-4o-mini",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": query},
                ],
                response_format={"type": "json_object"},
                temperature=0,
                max_tokens=300,
            )
            raw = response.choices[0].message.content
            result = json.loads(raw)
            result.setdefault("intent", "unknown")
            result.setdefault("language", state.language)
            result.setdefault("missing_slots", [])
            result.setdefault("confidence", 0.5)
            return result
        except Exception as exc:
            logger.error(f"LLM state update failed: {exc}")
            missing = [
                slot for slot, val in [
                    ("origin", state.origin),
                    ("destination", state.destination),
                    ("appointment_time", state.appointment_time),
                ]
                if not val
            ]
            return {
                "intent": "unknown",
                "language": state.language,
                "origin": state.origin,
                "destination": state.destination,
                "appointment_time": state.appointment_time,
                "time_mode": state.time_mode,
                "missing_slots": missing,
                "follow_up_question": (
                    "Bitte nennen Sie Abfahrtsort, Ziel und Zeitpunkt der Reise."
                    if missing else None
                ),
                "confidence": 0.0,
            }

    def _apply_llm_state(self, llm_state: dict, state: TravelPlanningState) -> None:
        """Merges the LLM-returned state update into the local TravelPlanningState.

        Null values never overwrite existing slots.
        """
        if llm_state.get("language"):
            state.language = llm_state["language"]
        for attr in ("origin", "destination", "appointment_time"):
            value = llm_state.get(attr)
            if value:
                setattr(state, attr, value)
        if llm_state.get("time_mode") and llm_state["time_mode"] != "unknown":
            state.time_mode = llm_state["time_mode"]

    async def _render_user_response_with_llm(
        self, response_type: str, language: str, payload: dict
    ) -> str:
        """Generates all user-facing text using an LLM.

        The LLM receives only structured facts from the payload. It is
        strictly prohibited from inventing offers, prices, transactions,
        or policy decisions. All factual content comes from the payload.
        """
        payload_json = json.dumps(payload, ensure_ascii=False, indent=2)

        system_prompt = (
            f"You are the response formatter for an enterprise business travel planning system.\n"
            f"Generate a response in language='{language}', response type='{response_type}'.\n\n"

            "STRICT FORMATTING RULES — never violate:\n"
            "- PLAIN TEXT ONLY. No **bold**, *italic*, # headers, or any other Markdown.\n"
            "- Section titles: ALL-CAPS on their own line, followed by a blank line.\n"
            "- Separate sections with a blank line.\n"
            "- Use actual German umlauts: ä, ö, ü, Ä, Ö, Ü, ß. Never write ae/oe/ue.\n"
            "- Use ONLY facts from the payload. Invent nothing.\n"
            "- Never change offer IDs, prices, durations, or provider names.\n"
            "- Label offer IDs as 'Angebot:'. Never write 'offer_id:'.\n\n"

            "FOR RESPONSE TYPE 'policy_decision' — output exactly these six sections in order:\n\n"

            "Section 1 — POLICY-ENTSCHEIDUNG\n"
            "Write: 'Die Auswahl wurde vom BusinessTravelPolicy Smart Contract via SmartContractClient "
            "getroffen, nicht von mir.'\n\n"

            "Section 2 — AUSGEWÄHLTE OPTION\n"
            "Always show: Angebot (offer_id), Typ (human-readable), Preis (total_price EUR), "
            "Dauer (duration_minutes Minuten).\n"
            "For mode='rail': Typ='Bahn'. Also show Anbieter-Agent (provider field), "
            "Betreiber (operator if present), Reiseklasse.\n"
            "For mode='flight_with_transfers': Typ='Kombiniertes Flug- und Transferangebot'.\n"
            "  Write 'Zusammengesetzt aus:' with two bullet lines:\n"
            "    - FlightProviderAgent: Flugangebot\n"
            "    - MobilityProviderAgent: Transferinformationen\n"
            "  Write 'Gesamt:' block with Gesamtpreis (total_price EUR) and "
            "Gesamtdauer (duration_minutes Minuten).\n"
            "  Write 'Bausteine:' with exactly 3 numbered entries:\n"
            "    1. Transfer zum Abflughafen\n"
            "       Anbieter-Agent: MobilityProviderAgent\n"
            "       Route: transfer_details.origin_to_airport.from -> "
            "transfer_details.origin_to_airport.to  (if present)\n"
            "       Preis: transfer_details.origin_to_airport.price EUR  (if present)\n"
            "       Dauer: transfer_details.origin_to_airport.duration_minutes Minuten  (if present)\n"
            "    2. Flug\n"
            "       Anbieter-Agent: FlightProviderAgent\n"
            "       Betreiber/Carrier: carrier field\n"
            "       Route: departure_airport -> arrival_airport  (if present)\n"
            "       Flugpreis: nicht separat ausgewiesen\n"
            "    3. Transfer am Zielort\n"
            "       Anbieter-Agent: MobilityProviderAgent\n"
            "       Route: transfer_details.airport_to_destination.from -> "
            "transfer_details.airport_to_destination.to  (if present)\n"
            "       Preis: transfer_details.airport_to_destination.price EUR  (if present)\n"
            "       Dauer: transfer_details.airport_to_destination.duration_minutes Minuten  (if present)\n"
            "  Skip any sub-field line if the value is absent from the payload.\n\n"

            "Section 3 — ENTSCHEIDUNGSGRUND\n"
            "Restate decision_reason from payload naturally in the response language. "
            "Do not claim the contract returns detailed reason codes.\n\n"

            "Section 4 — ALTERNATIVEN\n"
            "List each entry in valid_alternatives numbered.\n"
            "For each: Angebot (offer_id), Typ, Preis (EUR), Dauer (Minuten).\n"
            "For flight_with_transfers: add 'Zusammengesetzt aus: FlightProviderAgent + MobilityProviderAgent'.\n"
            "End each with: 'Einordnung: Policy-konform, aber nicht ausgewählt.'\n"
            "If list is empty: write 'Keine gültigen Alternativen.'\n\n"

            "Section 5 — ABGELEHNTE OPTIONEN\n"
            "List each entry in rejected_options numbered.\n"
            "Look up the offer_id in considered_offers to get full offer details "
            "(mode, total_price, duration_minutes, provider).\n"
            "For each: Angebot (offer_id), Typ (human-readable from mode), "
            "Preis (total_price EUR from considered_offers), "
            "Dauer (duration_minutes Minuten from considered_offers).\n"
            "End each entry with: 'Status: Vom BusinessTravelPolicy Contract abgelehnt. "
            "Detaillierte Reason Codes werden in der aktuellen Contract-Version nicht zurückgegeben.'\n"
            "If list is empty: write 'Keine abgelehnten Optionen.'\n\n"

            "Section 6 — NÄCHSTER SCHRITT\n"
            "Write: 'Es wurde noch keine Buchung erstellt. Wenn Sie diese Option simuliert "
            "und policy-verifiziert buchen möchten, schreiben Sie: buchen'\n\n"

            "FOR RESPONSE TYPE 'booking_submitted':\n"
            "Write these three sentences first (exactly as shown, with correct German umlauts):\n"
            "  'Es wurde keine echte Reisebuchung und keine echte Zahlung durchgeführt.'\n"
            "  'Eine Sepolia-Testnet-Transaktion für eine simulierte, policy-verifizierte "
            "Buchung wurde erstellt.'\n"
            "  'Der Provider-Agent hat eine simulierte Buchungsbestätigung zurückgegeben.'\n"
            "Then show from payload: Angebot (selectedOfferId), Betrag (amountEth ETH), "
            "Transaktions-Hash (transactionHash), Etherscan-Link (etherscanUrl), "
            "Policy-Verifiziert (policyVerified).\n\n"

            "FOR RESPONSE TYPE 'booking_without_plan':\n"
            "Ask the user to first submit a travel request so a policy-compliant offer can be selected.\n\n"

            "FOR RESPONSE TYPE 'planning_error':\n"
            "Report the error from payload and suggest verifying that all provider agents are running.\n\n"

            f"Payload:\n{payload_json}"
        )

        try:
            response = await self._get_openai().chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "system", "content": system_prompt}],
                temperature=0,
                max_tokens=1400,
            )
            return response.choices[0].message.content or "(leer)"
        except Exception as exc:
            logger.error(f"LLM response rendering failed: {exc}")
            return json.dumps(
                {"response_type": response_type, "payload": payload},
                ensure_ascii=False,
            )

    # -----------------------------------------------------------------------
    # Provider booking simulation
    # -----------------------------------------------------------------------

    async def _simulate_provider_booking(self, selected_offer: dict) -> dict:
        """Calls the matching provider agent via A2A for a booking simulation.

        This is a simulation only. No real travel booking is created.
        """
        offer_id = selected_offer.get("id") or selected_offer.get("offer_id")
        mode = selected_offer.get("mode")
        payload = {"action": "book", "offer_id": offer_id}

        try:
            if mode == "rail":
                return await self._call_provider_agent(self._rail_url, payload)
            if mode == "flight_with_transfers":
                return await self._call_provider_agent(self._flight_url, payload)
            return {
                "offerId": offer_id, "provider": "not available",
                "status": "not_available",
                "message": f"No provider booking simulation for mode: {mode}",
            }
        except Exception as exc:
            logger.error(f"Provider booking simulation failed: {exc}")
            return {
                "offerId": offer_id, "provider": "not available",
                "status": "failed", "message": str(exc),
            }

    # -----------------------------------------------------------------------
    # Main invoke
    # -----------------------------------------------------------------------

    async def invoke(self, query: str, context_id: str | None = None) -> tuple[str, bool]:
        """Processes one business travel message.

        All offer selection is delegated to SmartContractClient.
        All user-facing text is generated by _render_user_response_with_llm.
        """
        logger.info(f"BusinessTravelAgent received: {query} (context: {context_id})")
        context_key = context_id or "default"
        state = self._get_state(context_key)

        llm_state = await self._update_travel_state_with_llm(query, state)

        intent = llm_state.get("intent", "unknown")

        # plan_trip starts fresh: clear trip state so slots from a previous trip
        # never carry over into a new request.
        if intent == "plan_trip":
            state.origin = None
            state.destination = None
            state.appointment_time = None
            state.time_mode = "unknown"
            state.selected_offer = None
            state.policy_decision = None

        self._apply_llm_state(llm_state, state)

        lang = state.language

        # Booking intent
        if intent == "book_selected_offer":
            if not state.policy_decision:
                response = await self._render_user_response_with_llm(
                    "booking_without_plan", lang, {}
                )
                return response, False

            try:
                booking_result = submit_verified_booking_for_decision(state.policy_decision)
            except BookingClientError as exc:
                response = await self._render_user_response_with_llm(
                    "planning_error", lang, {"error": str(exc)}
                )
                return response, False

            booking_result["providerBooking"] = await self._simulate_provider_booking(
                state.selected_offer
            )
            response = await self._render_user_response_with_llm(
                "booking_submitted", lang, booking_result
            )
            return response, False

        # Missing slots — follow_up_question comes from the LLM state update
        missing = llm_state.get("missing_slots", [])
        if missing:
            follow_up = llm_state.get("follow_up_question")
            if not follow_up:
                follow_up = await self._render_user_response_with_llm(
                    "missing_slots", lang,
                    {
                        "missing_slots": missing,
                        "current_state": {
                            "origin": state.origin,
                            "destination": state.destination,
                            "appointment_time": state.appointment_time,
                        },
                    },
                )
            return follow_up, True

        # All slots complete — fetch offers, delegate selection to SmartContractClient
        try:
            offers = await self._build_offers(
                state.origin, state.destination, state.appointment_time
            )
            logger.info("Calling SmartContractClient.select_policy_compliant_offer")
            decision = self._smart_contract.select_policy_compliant_offer(offers)
            state.selected_offer = decision.get("selected_offer")
            state.policy_decision = decision
            logger.info(
                "SmartContractClient selected: "
                f"{state.selected_offer.get('offer_id') if state.selected_offer else 'None'}"
            )
        except Exception as exc:
            logger.error(f"Travel planning failed: {exc}")
            state.selected_offer = None
            state.policy_decision = None
            response = await self._render_user_response_with_llm(
                "planning_error", lang,
                {
                    "error": str(exc),
                    "origin": state.origin,
                    "destination": state.destination,
                    "appointment_time": state.appointment_time,
                },
            )
            return response, False

        response = await self._render_user_response_with_llm("policy_decision", lang, decision)
        return response, False
