# agents/business_travel/agent.py

import json
import logging
import uuid
from typing import Any

from a2a.client import ClientFactory
from a2a.types import Message, Part, Role, SendMessageRequest
from openai import AsyncOpenAI

from utilities.blockchain.business_agent_registry_discovery import (
    discover_all_provider_endpoints,
)
from utilities.blockchain.business_travel_booking_client import (
    BookingClientError,
    submit_verified_booking_for_decision,
)
from utilities.smart_contract.smart_contract_client import SmartContractClient

logger = logging.getLogger(__name__)


class TravelPlanningState:
    """Per-context state for a multi-turn business travel conversation."""

    def __init__(self):
        self.origin: str | None = None
        self.destination: str | None = None
        self.appointment_time: str | None = None
        self.time_mode: str = "unknown"
        self.language: str = "de"
        self.selected_offer: dict | None = None
        self.policy_decision: dict | None = None


class BusinessTravelAgent:
    """Coordinates business travel planning via A2A provider agents.

    Architecture contracts:
    - Provider agents supply raw travel offers via A2A.
    - SmartContractClient makes the final policy-based offer selection.
    - All user-facing text is generated by the LLM (_render_user_response_with_llm).
    - The LLM never selects offers, evaluates prices, or applies policy.
    """

    SUPPORTED_CONTENT_TYPES = ["text", "text/plain"]

    def __init__(self):
        self._smart_contract = SmartContractClient()
        self._sessions: dict[str, TravelPlanningState] = {}
        self._provider_clients: dict[str, Any] = {}
        self._openai: AsyncOpenAI | None = None

        endpoints = discover_all_provider_endpoints(use_fallback=False)
        self._rail_url: str = self._require_provider_endpoint(endpoints, "rail")
        self._flight_url: str = self._require_provider_endpoint(endpoints, "flight")
        self._mobility_url: str = self._require_provider_endpoint(endpoints, "mobility")
        logger.info(
            "Provider endpoints resolved via registry: rail=%s flight=%s mobility=%s",
            self._rail_url, self._flight_url, self._mobility_url,
        )

    @staticmethod
    def _require_provider_endpoint(endpoints: dict, capability: str) -> str:
        """Returns the discovered endpoint or raises RuntimeError — no local fallback."""
        endpoint, error = endpoints[capability]
        if endpoint is None:
            raise RuntimeError(
                f"No active provider endpoint found in BusinessAgentRegistry for "
                f"capability '{capability}'. "
                "Provider discovery must succeed via blockchain registry. "
                f"No local fallback is allowed. Reason: {error}"
            )
        return endpoint

    def _get_state(self, context_id: str) -> TravelPlanningState:
        if context_id not in self._sessions:
            self._sessions[context_id] = TravelPlanningState()
        return self._sessions[context_id]

    def _get_openai(self) -> AsyncOpenAI:
        """Returns the shared AsyncOpenAI client, creating it lazily on first use."""
        if self._openai is None:
            self._openai = AsyncOpenAI()
        return self._openai

    # -----------------------------------------------------------------------
    # A2A provider calls
    # -----------------------------------------------------------------------

    async def _call_provider_agent(self, agent_url: str, payload: dict) -> Any:
        """Sends a JSON payload to a provider agent via A2A and returns parsed JSON."""
        if agent_url not in self._provider_clients:
            factory = ClientFactory()
            self._provider_clients[agent_url] = await factory.create_from_url(agent_url)
        client = self._provider_clients[agent_url]

        request = SendMessageRequest(
            message=Message(
                message_id=uuid.uuid4().hex,
                role=Role.ROLE_USER,
                parts=[Part(text=json.dumps(payload, ensure_ascii=False))],
                context_id="",
            )
        )

        response_parts: list[str] = []
        async for result in client.send_message(request):
            field = result.WhichOneof("payload")
            if field == "message":
                for part in result.message.parts:
                    if getattr(part, "text", None):
                        response_parts.append(part.text)
            elif field == "task":
                if result.task.status.HasField("message"):
                    for part in result.task.status.message.parts:
                        if getattr(part, "text", None):
                            response_parts.append(part.text)

        combined = "\n".join(response_parts)
        try:
            return json.loads(combined)
        except json.JSONDecodeError as exc:
            raise ValueError(
                f"Provider agent at {agent_url} returned non-JSON: {combined[:200]}"
            ) from exc

    async def _search_rail_options(
        self, origin: str, destination: str, appointment_time: str
    ) -> list[dict]:
        logger.info(f"Calling RailProviderAgent: {origin} -> {destination}")
        result = await self._call_provider_agent(self._rail_url, {
            "origin": origin, "destination": destination, "appointment_time": appointment_time,
        })
        return result if isinstance(result, list) else []

    async def _search_flight_options(
        self, origin: str, destination: str, appointment_time: str
    ) -> list[dict]:
        logger.info(f"Calling FlightProviderAgent: {origin} -> {destination}")
        result = await self._call_provider_agent(self._flight_url, {
            "origin": origin, "destination": destination, "appointment_time": appointment_time,
        })
        return result if isinstance(result, list) else []

    async def _get_airport_transfers(
        self,
        origin: str,
        destination: str,
        departure_airport: str,
        arrival_airport: str,
    ) -> dict:
        logger.info(f"Calling MobilityProviderAgent: {departure_airport} -> {arrival_airport}")
        result = await self._call_provider_agent(self._mobility_url, {
            "origin": origin, "destination": destination,
            "departure_airport": departure_airport, "arrival_airport": arrival_airport,
        })
        return result if isinstance(result, dict) else {}

    # -----------------------------------------------------------------------
    # Offer preparation
    # -----------------------------------------------------------------------

    def _combine_flight_with_transfers(self, flight: dict, transfers: dict) -> dict:
        """Builds a single policy-checkable offer from a flight and its transfer data."""
        return {
            "offer_id": f"{flight['offer_id']}-with-transfers",
            "mode": "flight_with_transfers",
            "provider": flight["provider"],
            "carrier": flight.get("carrier"),
            "total_price": flight["flight_price"] + transfers.get("total_transfer_price", 0),
            "duration_minutes": (
                flight["flight_duration_minutes"]
                + transfers.get("total_transfer_duration_minutes", 0)
            ),
            "travel_class": flight["travel_class"],
            "provider_reputation": flight["provider_reputation"],
            "arrival_buffer_minutes": flight["arrival_buffer_minutes"],
            "transfers_included": transfers.get("transfers_available") is True,
            "departure_airport": flight["departure_airport"],
            "arrival_airport": flight["arrival_airport"],
            "transfer_details": transfers,
        }

    async def _build_offers(
        self, origin: str, destination: str, appointment_time: str
    ) -> list[dict]:
        """Collects rail and flight-with-transfer offers for SmartContractClient.

        All offer types are always fetched. Policy decisions (rail preference,
        budget, class) belong exclusively to SmartContractClient.
        """
        rail_options = await self._search_rail_options(origin, destination, appointment_time)

        flight_options = await self._search_flight_options(origin, destination, appointment_time)
        combined_flights: list[dict] = []
        for flight in flight_options:
            if flight.get("departure_airport") and flight.get("arrival_airport"):
                transfers = await self._get_airport_transfers(
                    origin, destination,
                    flight["departure_airport"],
                    flight["arrival_airport"],
                )
                combined_flights.append(self._combine_flight_with_transfers(flight, transfers))

        return rail_options + combined_flights

    # -----------------------------------------------------------------------
    # LLM: state update and response rendering
    # -----------------------------------------------------------------------

    async def _update_travel_state_with_llm(
        self, query: str, state: TravelPlanningState
    ) -> dict:
        """Returns a complete merged travel state from the current context + new message.

        The LLM sees the full current state and new user input, then returns a
        single merged JSON state including missing_slots and follow_up_question.
        Offer selection, policy evaluation, and pricing remain in SmartContractClient.
        """
        system_prompt = (
            "You are a travel intent parser for a business travel system.\n"
            "You receive the current known travel state and a new user message.\n"
            "Return a merged, updated state as strict JSON with exactly these keys:\n\n"
            '{\n'
            '  "intent": "plan_trip" | "book_selected_offer" | "modify_trip" | "unknown",\n'
            '  "language": "de" | "en",\n'
            '  "origin": <city string or null>,\n'
            '  "destination": <city string or null>,\n'
            '  "appointment_time": <complete string e.g. "Montag 10 Uhr", "morgen 14:30", or null>,\n'
            '  "time_mode": "departure" | "arrival" | "unknown",\n'
            '  "missing_slots": [<slot names still null: "origin", "destination", "appointment_time">],\n'
            '  "follow_up_question": <natural language question for user if slots are missing, else null>,\n'
            '  "confidence": <0.0-1.0>\n'
            '}\n\n'
            "Rules:\n"
            "- Merge the current state with new information from the user message.\n"
            "- Do NOT clear existing slots unless intent is 'modify_trip' and the user explicitly replaces a slot.\n"
            "- 'missing_slots' must list every slot that is still null after merging.\n"
            "- 'follow_up_question' must be in the detected language and ask only for the missing slots.\n"
            "- If all required slots are filled: 'missing_slots' must be [] and 'follow_up_question' must be null.\n"
            "- For 'book_selected_offer': 'missing_slots' must be [] regardless of state.\n"
            "- You MUST NOT select offers, evaluate prices, apply policy, or invent travel options.\n\n"
            "Current state:\n"
            f"origin={state.origin or 'null'}, destination={state.destination or 'null'}, "
            f"appointment_time={state.appointment_time or 'null'}, language={state.language}"
        )

        try:
            response = await self._get_openai().chat.completions.create(
                model="gpt-4o-mini",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": query},
                ],
                response_format={"type": "json_object"},
                temperature=0,
                max_tokens=300,
            )
            raw = response.choices[0].message.content
            result = json.loads(raw)
            result.setdefault("intent", "unknown")
            result.setdefault("language", state.language)
            result.setdefault("missing_slots", [])
            result.setdefault("confidence", 0.5)
            return result
        except Exception as exc:
            logger.error(f"LLM state update failed: {exc}")
            missing = [
                slot for slot, val in [
                    ("origin", state.origin),
                    ("destination", state.destination),
                    ("appointment_time", state.appointment_time),
                ]
                if not val
            ]
            return {
                "intent": "unknown",
                "language": state.language,
                "origin": state.origin,
                "destination": state.destination,
                "appointment_time": state.appointment_time,
                "time_mode": state.time_mode,
                "missing_slots": missing,
                "follow_up_question": (
                    "Bitte nennen Sie Abfahrtsort, Ziel und Zeitpunkt der Reise."
                    if missing else None
                ),
                "confidence": 0.0,
            }

    def _apply_llm_state(self, llm_state: dict, state: TravelPlanningState) -> None:
        """Merges the LLM-returned state update into the local TravelPlanningState.

        Null values never overwrite existing slots.
        """
        if llm_state.get("language"):
            state.language = llm_state["language"]
        for attr in ("origin", "destination", "appointment_time"):
            value = llm_state.get(attr)
            if value:
                setattr(state, attr, value)
        if llm_state.get("time_mode") and llm_state["time_mode"] != "unknown":
            state.time_mode = llm_state["time_mode"]

    async def _render_user_response_with_llm(
        self, response_type: str, language: str, payload: dict
    ) -> str:
        """Generates all user-facing text using an LLM.

        The LLM receives only structured facts from the payload. It is
        strictly prohibited from inventing offers, prices, transactions,
        or policy decisions. All factual content comes from the payload.
        """
        payload_json = json.dumps(payload, ensure_ascii=False, indent=2)

        system_prompt = (
            f"You are the response formatter for a business travel planning system.\n"
            f"Generate a clear, structured response in language='{language}'.\n"
            f"Response type: '{response_type}'.\n\n"
            "STRICT RULES — never violate these:\n"
            "- Use ONLY the facts in the payload below. Invent nothing.\n"
            "- Never change selected offer, prices, durations, or provider names.\n"
            "- Never invent missing fields or add assumptions.\n"
            "- For 'policy_decision': State clearly that the selection was made by "
            "the deployed BusinessTravelPolicy contract via SmartContractClient, not by you. Show: selected offer "
            "(offer_id, mode, price, duration), decision reason, valid alternatives "
            "with why they were not selected, rejected options with rejection reasons, "
            "booking approval status. End by stating no booking or payment has been executed.\n"
            "- For 'booking_submitted': State clearly this is a Sepolia testnet simulation "
            "and no real travel booking was made.\n"
            "- For 'booking_without_plan': Ask the user to plan a trip first.\n"
            "- For 'planning_error': Report the error and suggest checking provider agents.\n"
            "- Keep the response concise and well-structured with clear headings.\n\n"
            f"Payload:\n{payload_json}"
        )

        try:
            response = await self._get_openai().chat.completions.create(
                model="gpt-4o-mini",
                messages=[{"role": "system", "content": system_prompt}],
                temperature=0,
                max_tokens=800,
            )
            return response.choices[0].message.content or "(leer)"
        except Exception as exc:
            logger.error(f"LLM response rendering failed: {exc}")
            return json.dumps(
                {"response_type": response_type, "payload": payload},
                ensure_ascii=False,
            )

    # -----------------------------------------------------------------------
    # Provider booking simulation
    # -----------------------------------------------------------------------

    async def _simulate_provider_booking(self, selected_offer: dict) -> dict:
        """Calls the matching provider agent via A2A for a booking simulation.

        This is a simulation only. No real travel booking is created.
        """
        offer_id = selected_offer.get("id") or selected_offer.get("offer_id")
        mode = selected_offer.get("mode")
        payload = {"action": "book", "offer_id": offer_id}

        try:
            if mode == "rail":
                return await self._call_provider_agent(self._rail_url, payload)
            if mode == "flight_with_transfers":
                return await self._call_provider_agent(self._flight_url, payload)
            return {
                "offerId": offer_id, "provider": "not available",
                "status": "not_available",
                "message": f"No provider booking simulation for mode: {mode}",
            }
        except Exception as exc:
            logger.error(f"Provider booking simulation failed: {exc}")
            return {
                "offerId": offer_id, "provider": "not available",
                "status": "failed", "message": str(exc),
            }

    # -----------------------------------------------------------------------
    # Main invoke
    # -----------------------------------------------------------------------

    async def invoke(self, query: str, context_id: str | None = None) -> tuple[str, bool]:
        """Processes one business travel message.

        All offer selection is delegated to SmartContractClient.
        All user-facing text is generated by _render_user_response_with_llm.
        """
        logger.info(f"BusinessTravelAgent received: {query} (context: {context_id})")
        context_key = context_id or "default"
        state = self._get_state(context_key)

        llm_state = await self._update_travel_state_with_llm(query, state)
        self._apply_llm_state(llm_state, state)

        intent = llm_state.get("intent", "unknown")
        lang = state.language

        # Booking intent
        if intent == "book_selected_offer":
            if not state.policy_decision:
                response = await self._render_user_response_with_llm(
                    "booking_without_plan", lang, {}
                )
                return response, False

            try:
                booking_result = submit_verified_booking_for_decision(state.policy_decision)
            except BookingClientError as exc:
                response = await self._render_user_response_with_llm(
                    "planning_error", lang, {"error": str(exc)}
                )
                return response, False

            booking_result["providerBooking"] = await self._simulate_provider_booking(
                state.selected_offer
            )
            response = await self._render_user_response_with_llm(
                "booking_submitted", lang, booking_result
            )
            return response, False

        # Missing slots — follow_up_question comes from the LLM state update
        missing = llm_state.get("missing_slots", [])
        if missing:
            follow_up = llm_state.get("follow_up_question")
            if not follow_up:
                follow_up = await self._render_user_response_with_llm(
                    "missing_slots", lang,
                    {
                        "missing_slots": missing,
                        "current_state": {
                            "origin": state.origin,
                            "destination": state.destination,
                            "appointment_time": state.appointment_time,
                        },
                    },
                )
            return follow_up, True

        # All slots complete — fetch offers, delegate selection to SmartContractClient
        try:
            offers = await self._build_offers(
                state.origin, state.destination, state.appointment_time
            )
            logger.info("Calling SmartContractClient.select_policy_compliant_offer")
            decision = self._smart_contract.select_policy_compliant_offer(offers)
            state.selected_offer = decision.get("selected_offer")
            state.policy_decision = decision
            logger.info(
                "SmartContractClient selected: "
                f"{state.selected_offer.get('offer_id') if state.selected_offer else 'None'}"
            )
        except Exception as exc:
            logger.error(f"Travel planning failed: {exc}")
            state.selected_offer = None
            state.policy_decision = None
            response = await self._render_user_response_with_llm(
                "planning_error", lang,
                {
                    "error": str(exc),
                    "origin": state.origin,
                    "destination": state.destination,
                    "appointment_time": state.appointment_time,
                },
            )
            return response, False

        response = await self._render_user_response_with_llm("policy_decision", lang, decision)
        return response, False
